spring:
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8083

jwt:
  secretKey: ${JWT_SECRET_KEY:asdjfkasdhfjkashdfkashdfkahsdjkfahskdf}
  accessExpiredExp: ${JWT_ACCESS_EXP:1800000}
  refreshExpiredExp: ${JWT_REFRESH_EXP:432000000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}